name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      - staging

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Stel environment variabelen in op basis van de branch
      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "REACT_APP_BACKGROUND_COLOR=${{ secrets.PRODUCTION_COLOR }}" >> .env
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "REACT_APP_BACKGROUND_COLOR=${{ secrets.STAGING_COLOR }}" >> .env
          fi

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_0E092D210 }}
          action: "upload"
          app_location: "./les6_klassikaal" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          github_id_token: ${{ secrets.GITHUB_ID_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
